version: '3.4'

services:

  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    # image: zookeeper:3.4.9
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    ports:
      - "2181:2181"
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_PORT: 2181
    #   ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    hostname: kafka
    container_name: kafka
    # image: confluentinc/cp-kafka:5.5.1
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    healthcheck:
      test: "/opt/kafka/bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9093 --list"
      start_period: 0s
      interval: 30s
      timeout: 2m
      retries: 10
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
